{"name": "test_generic_exception_handling", "status": "passed", "description": "Test handling of unexpected exceptions", "attachments": [{"name": "log", "source": "3cae5a50-7fb2-460e-a7d0-3163c19baf31-attachment.txt", "type": "text/plain"}], "start": 1757668149718, "stop": 1757668149719, "uuid": "e3571a08-f273-40f4-840e-c890f08b18ed", "historyId": "a5b672efd0119cb4cf92554c5c33f034", "testCaseId": "a5b672efd0119cb4cf92554c5c33f034", "fullName": "tests.unit.test_llm_adapters_comprehensive.TestOpenAIAdapter#test_generic_exception_handling", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestOpenAIAdapter"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "33649-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "unit", "test_llm_adapters_comprehensive.py", "TestOpenAIAdapter"]}