{"name": "test_retry_on_timeout", "status": "broken", "statusDetails": {"message": "ImportError: cannot import name 'RecoveryError' from 'app.utils.errors' (unknown location)", "trace": "tests/unit/test_recovery_service.py:7: in test_retry_on_timeout\n    from app.services.recovery_service import RecoveryService, RecoveryType\napp/services/recovery_service.py:19: in <module>\n    from app.utils.errors import RecoveryError, SystemError\nE   ImportError: cannot import name 'RecoveryError' from 'app.utils.errors' (unknown location)"}, "start": 1757668162289, "stop": 1757668162290, "uuid": "d03db0b0-6cde-4b04-bf6c-0e5c4f2d3fdc", "historyId": "e0c441deefc0d1dc5fd363c61d5a7d6c", "testCaseId": "e0c441deefc0d1dc5fd363c61d5a7d6c", "fullName": "tests.unit.test_recovery_service#test_retry_on_timeout", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_recovery_service"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "34209-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_recovery_service"}], "titlePath": ["tests", "unit", "test_recovery_service.py"]}