{"name": "test_invalid_auth_rejected", "status": "passed", "description": "Test that invalid authentication is rejected", "attachments": [{"name": "log", "source": "ff365a9c-5d9b-4560-b8f8-336fe1faa49f-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "6f8cc6f4-91b3-4eb0-9ee4-2ee84e420ffe-attachment.txt", "type": "text/plain"}], "start": 1757657434638, "stop": 1757657434640, "uuid": "17d0203e-69b9-48a4-82e8-8b5878d55117", "historyId": "58ffc6d127f36ef7ed128c248c5e95c1", "testCaseId": "58ffc6d127f36ef7ed128c248c5e95c1", "fullName": "tests.test_auth_rate_limit.TestAuthMiddleware#test_invalid_auth_rejected", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_rate_limit"}, {"name": "subSuite", "value": "TestAuthMiddleware"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "59211-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_rate_limit"}], "titlePath": ["tests", "test_auth_rate_limit.py", "TestAuthMiddleware"]}