{"name": "test_openai_adapter_authentication_error", "status": "passed", "description": "Test OpenAI adapter handles 401 authentication errors.", "attachments": [{"name": "log", "source": "d6b314eb-6b27-47ef-a86d-999a7f39cfc5-attachment.txt", "type": "text/plain"}], "start": 1757711142110, "stop": 1757711142112, "uuid": "88933a42-8b15-457c-a59c-75f3227e89b7", "historyId": "3cddc73f16fe29d39bdbf3d11652e1e9", "testCaseId": "3cddc73f16fe29d39bdbf3d11652e1e9", "fullName": "tests.test_llm_adapters_comprehensive.TestOpenAIAdapter#test_openai_adapter_authentication_error", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestOpenAIAdapter"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "99272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "test_llm_adapters_comprehensive.py", "TestOpenAIAdapter"]}