{"name": "test_retry_on_timeout", "status": "passed", "description": "Test that recovery service retries on timeout errors.", "start": 1757656823942, "stop": 1757656823943, "uuid": "92ee5d58-3792-4ec2-ae28-2f9c9d256943", "historyId": "8837a77c0d3662da33c2b12bf4b0b2cb", "testCaseId": "8837a77c0d3662da33c2b12bf4b0b2cb", "fullName": "tests.unit.test_recovery_service_simple#test_retry_on_timeout", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_recovery_service_simple"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "37492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_recovery_service_simple"}], "titlePath": ["tests", "unit", "test_recovery_service_simple.py"]}