{"name": "test_retry_on_timeout", "status": "passed", "description": "Test that recovery service retries on timeout errors.", "start": 1757668149921, "stop": 1757668149921, "uuid": "09c7c16c-9f94-4ac0-b7ac-a28e8cb8e28f", "historyId": "8837a77c0d3662da33c2b12bf4b0b2cb", "testCaseId": "8837a77c0d3662da33c2b12bf4b0b2cb", "fullName": "tests.unit.test_recovery_service_simple#test_retry_on_timeout", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_recovery_service_simple"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "33649-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_recovery_service_simple"}], "titlePath": ["tests", "unit", "test_recovery_service_simple.py"]}